import os

base = r'D:\0code\haifeng\fronted\HaiFeng-Fronted\apps\admin\src\views'
files = [
    'algorithm/admission/group/index.vue',
    'certificate/certificate/index.vue',
    'certificate/competition-major/index.vue',
    'certificate/competition/index.vue',
    'employment/civil/index.vue',
    'employment/community/index.vue',
    'employment/content/guide/index.vue',
    'employment/content/notice/index.vue',
    'employment/finance/index.vue',
    'employment/grassroots/index.vue',
    'employment/healthcare/index.vue',
    'employment/institution/index.vue',
    'employment/military/index.vue',
    'employment/selection/index.vue',
    'employment/teacher/index.vue',
    'employment/welfare/index.vue',
]

FF = '\ufffd'
QM = '?'

prefix_fixes = {
    # Patterns corrupted by byte loss
    FF + QM + '仅支持': '仅支持',
    FF + QM + '：': '如：',
    FF + QM + ' fa': '如: fa',
    '已结' + FF + QM: '已结束',
    '招募' + FF + QM: '招募中',
    '招聘' + FF + QM: '招聘中',
    '进行' + FF + QM: '进行中',
    '即将开' + FF + QM: '即将开始',
    '备考攻' + FF + QM: '备考攻略',
    '信息技' + FF + QM: '信息技术',
    '通用技' + FF + QM: '通用技术',
    '一级乙' + FF + QM: '一级乙等',
    '一级甲' + FF + QM: '一级甲等',
    '幼儿' + FF + QM: '幼儿园',
    '专业组代' + FF + QM: '专业组代码',
    '专业组名' + FF + QM: '专业组名称',
    '专业组简' + FF + QM: '专业组简介',
    '专业组详' + FF + QM: '专业组详情',
    '可转事业' + FF + QM: '可转事业编',
    '居住地要' + FF + QM: '居住地要求',
    '月补贴标' + FF + QM: '月补贴标准',
    '社工证要' + FF + QM: '社工证要求',
    '考试与地' + FF + QM: '考试与地点',
    '考试与报' + FF + QM: '考试与报名',
    '考试与时' + FF + QM: '考试与时间',
    '考试与补' + FF + QM: '考试与补录',
    '薪资与福' + FF + QM: '薪资与福利',
    '街道办事' + FF + QM: '街道办事处',
    '计算机要' + FF + QM: '计算机要求',
    '请输入摘' + FF + QM: '请输入摘要',
    '请输入标' + FF + QM: '请输入标题',
    '资格证学' + FF + QM: '资格证学历',
    '资质与待' + FF + QM: '资质与待遇',
    '零就业家' + FF + QM: '零就业家庭',
    '高校毕业' + FF + QM: '高校毕业生',
    '本科及以' + FF + QM: '本科及以上',
    '大专及以' + FF + QM: '大专及以上',
    '硕士及以' + FF + QM: '硕士及以上',
    '硬删' + FF + QM: '硬删除',
    '软删' + FF + QM: '软删除',
    '批量硬删' + FF + QM: '批量硬删除',
    '批量软删' + FF + QM: '批量软删除',
    '开始校' + FF + QM: '开始校验',
    '新增专业' + FF + QM: '新增专业组',
    '修改专业' + FF + QM: '修改专业组',
    '作者头' + FF + QM: '作者头像',
    '开发单' + FF + QM: '开发单位',
    '报名开' + FF + QM: '报名开始',
    '报名状' + FF + QM: '报名状态',
    '报考条' + FF + QM: '报考条件',
    '报考要' + FF + QM: '报考要求',
    '最低位' + FF + QM: '最低位次',
    '最低学' + FF + QM: '最低学历',
    '最高位' + FF + QM: '最高位次',
    '目标读' + FF + QM: '目标读者',
    '职位简' + FF + QM: '职位简介',
    '证书简' + FF + QM: '证书简介',
    '退役军' + FF + QM: '退役军人',
    '搜索' + FF + QM: '搜索',
    '操作' + FF + QM: '操作',
    '折叠' + FF + QM: '折叠',
    '状' + FF + QM: '状态',
    '月工' + FF + QM: '月工资',
    '封面' + FF + QM: '封面',
    '子分' + FF + QM: '子分类',
    '图标' + FF + QM: '图标',
    '可续' + FF + QM: '可续期',
    '副标' + FF + QM: '副标题',
    '阅读' + FF + QM: '阅读量',
    '点赞' + FF + QM: '点赞量',
    '联系' + FF + QM: '联系人',
    '输入报考条' + FF + QM: '输入报考条件',
    '输入专业大' + FF + QM: '输入专业大类',
    '输入目标院' + FF + QM: '输入目标院校',
    '输入竞赛名' + FF + QM: '输入竞赛名称',
    '输入证书名' + FF + QM: '输入证书名称',
    '输入证书简' + FF + QM: '输入证书简介',
    '填写专业名' + FF + QM: '填写专业名称',
    '填写竞赛名' + FF + QM: '填写竞赛名称',
    '填写证书名' + FF + QM: '填写证书名称',
    '硬删除竞赛' + FF + QM: '硬删除竞赛',
    '硬删除证书' + FF + QM: '硬删除证书',
    '硬删除选中' + FF + QM: '硬删除选中的',
    '软删除竞赛' + FF + QM: '软删除竞赛',
    '软删除证书' + FF + QM: '软删除证书',
    '软删除选中' + FF + QM: '软删除选中的',
    '要删除竞赛' + FF + QM: '要删除竞赛',
    '要删除选中' + FF + QM: '要删除选中的',
    '定删除选中' + FF + QM: '定删除选中的',
    '批量硬删' + FF + QM: '批量硬删除',
    '状态更新成' + FF + QM: '状态更新成功',
    '硬删除成' + FF + QM: '硬删除成功',
    '软删除成' + FF + QM: '软删除成功',
    '量软删除失' + FF + QM: '量软删除失败',
    '量软删除成' + FF + QM: '量软删除成功',
    '从列表隐藏' + FF + QM: '从列表隐藏',
    '作不可恢复' + FF + QM: '作不可恢复',
    '作不可撤销' + FF + QM: '作不可撤销',
    '作者岗位吗' + FF + QM: '作者岗位吗',
    '作者岗位详' + FF + QM: '作者岗位详情',
    '卫生岗位吗' + FF + QM: '卫生岗位吗',
    '招聘岗位吗' + FF + QM: '招聘岗位吗',
    '文职岗位吗' + FF + QM: '文职岗位吗',
    '益性岗位吗' + FF + QM: '益性岗位吗',
    '益性岗位详' + FF + QM: '益性岗位详情',
    '调生岗位吗' + FF + QM: '调生岗位吗',
    '调生岗位详' + FF + QM: '调生岗位详情',
    '修改备考指' + FF + QM: '修改备考指南',
    '务员职位详' + FF + QM: '务员职位详情',
    '务地点与要' + FF + QM: '务地点与要求',
    '区与报名要' + FF + QM: '区与报名要求',
    '区与报考要' + FF + QM: '区与报考要求',
    '备考指南详' + FF + QM: '备考指南详情',
    '改事业编职' + FF + QM: '改事业编职位',
    '改公务员职' + FF + QM: '改公务员职位',
    '改公益性岗' + FF + QM: '改公益性岗位',
    '改选调生岗' + FF + QM: '改选调生岗位',
    '位与岗位信' + FF + QM: '位与岗位信息',
    '位期限与待' + FF + QM: '位期限与待遇',
    '构与岗位信' + FF + QM: '构与岗位信息',
    '校与岗位信' + FF + QM: '校与岗位信息',
    '殊要求与待' + FF + QM: '殊要求与待遇',
    '目与岗位信' + FF + QM: '目与岗位信息',
    '遇与期满政' + FF + QM: '遇与期满政策',
    '最长服务年' + FF + QM: '最长服务年限',
    '服务开始日' + FF + QM: '服务开始日期',
    '束条件后回' + FF + QM: '束条件后回车',
    '入标签后回' + FF + QM: '入标签后回车',
    '格下车添' + FF + QM: '格，回车添加',
    '责下车添' + FF + QM: '责，回车添加',
    '格证学科要' + FF + QM: '格证学科要求',
    '师资格证要' + FF + QM: '师资格证要求',
    '业资格证要' + FF + QM: '业资格证要求',
    '业编职位详' + FF + QM: '业编职位详情',
    '无要' + FF + QM: '无要求',
    '不要' + FF + QM: '不要',
    '必' + FF + QM: '必备',
    '已结' + FF + QM: '已结束',
    '报名' + FF + QM: '报名中',
    '招募' + FF + QM: '招募中',
    '招聘' + FF + QM: '招聘中',
    '进行' + FF + QM: '进行中',
    '11月上' + FF + QM: '11月上旬',
    '如：5月中' + FF + QM: '如：5月中旬',
    '如：每年3' + FF + QM: '如：每年3月',
    '如：每年6' + FF + QM: '如：每年6月',
    '如：' + FF + QM: '如：',
    '拖到此处，' + FF + QM: '拖到此处，或',
    '仅支' + FF + QM: '仅支持',
    '则表示不限' + FF + QM: '则表示不限',
    '详情（选填' + FF + QM: '详情（选填）',
    '完整信息（' + FF + QM: '完整信息（',
    '（' + FF + QM: '（',
    '小学' + FF + QM: '小学',
    '中学' + FF + QM: '中学',
    '幼儿园' + FF + QM: '幼儿园',
    '合同制' + FF + QM: '合同制',
    '劳务派遣' + FF + QM: '劳务派遣',
    '直接面试' + FF + QM: '直接面试',
    '编制备案制' + FF + QM: '编制备案制',
    '纳入编制' + FF + QM: '纳入编制',
    '员额制' + FF + QM: '员额制',
    '控编' + FF + QM: '控编',
    'Android' + FF + QM: 'Android',
    'iOS' + FF + QM: 'iOS',
    'IT' + FF + QM: 'IT',
    'CPA' + FF + QM: 'CPA',
    'HTML' + FF + QM: 'HTML',
    '学历' + FF + QM: '学历',
    '学位' + FF + QM: '学位',
    '资格' + FF + QM: '资格',
    '全职' + FF + QM: '全职',
    '兼职' + FF + QM: '兼职',
    '实习' + FF + QM: '实习',
    '初级社工' + FF + QM: '初级社工',
    '中级社工' + FF + QM: '中级社工',
    '高级社工' + FF + QM: '高级社工',
    '更加' + FF + QM: '更加',
    '提交' + FF + QM: '提交',
    '保存' + FF + QM: '保存',
    '提示' + FF + QM: '提示',
    '确定' + FF + QM: '确定',
    '取消' + FF + QM: '取消',
    '成功' + FF + QM: '成功',
    '失败' + FF + QM: '失败',
    '暂无' + FF + QM: '暂无',
    '暂无数据' + FF + QM: '暂无数据',
    '禁用' + FF + QM: '禁用',
    '启用' + FF + QM: '启用',
    '启用中' + FF + QM: '启用中',
    '审核中' + FF + QM: '审核中',
    '正常' + FF + QM: '正常',
    "的" + FF + QM: '的',
    "公" + FF + QM: '公告',
    "通" + FF + QM: '通知',
    "删" + FF + QM: '删除',
    "修" + FF + QM: '修改',
    '添加' + FF + QM: '添加',
    '新增' + FF + QM: '新增',
    '查看' + FF + QM: '查看',
    '编辑' + FF + QM: '编辑',
    '详情' + FF + QM: '详情',
    '预览' + FF + QM: '预览',
    '导出' + FF + QM: '导出',
    '导入' + FF + QM: '导入',
    '上传' + FF + QM: '上传',
    '下载' + FF + QM: '下载',
    '刷新' + FF + QM: '刷新',
    '搜索' + FF + QM: '搜索',
    '重置' + FF + QM: '重置',
    '查询' + FF + QM: '查询',
    '行业' + FF + QM: '行业',
    '资源' + FF + QM: '资源',
    '标题' + FF + QM: '标题',
    '内容' + FF + QM: '内容',
    '分类' + FF + QM: '分类',
    '标签' + FF + QM: '标签',
    '关键字' + FF + QM: '关键字',
    '社区服务工' + FF + QM: '社区服务工作者',
    '社区党务工' + FF + QM: '社区党务工作者',
    '三支一' + FF + QM: '三支一扶',
    '公益性岗' + FF + QM: '公益性岗位',
    '妇幼保健' + FF + QM: '妇幼保健',
    '社会工作' + FF + QM: '社会工作',
    '道德与法' + FF + QM: '道德与法律',
    '公共管理' + FF + QM: '公共管理',
    '公共安全' + FF + QM: '公共安全',
    '公共服务' + FF + QM: '公共服务',
    '公共环境' + FF + QM: '公共环境',
    '社区安全' + FF + QM: '社区安全',
    '社区网格' + FF + QM: '社区网格',
    '社区调解' + FF + QM: '社区调解',
    '设施维护' + FF + QM: '设施维护',
    '竞赛背景与意' + FF + QM: '竞赛背景与意义',
    'Excel预校' + FF + QM: 'Excel预览',
    '所属局/' + FF + QM: '所属局/',
    '报名与补' + FF + QM: '报名与补录',
    '考试费用(' + FF + QM: '考试费用(',
    '字段' + FF + QM: '字段',
    '批量删除选中' + FF + QM: '批量删除选中的',
    '永久删除选中' + FF + QM: '永久删除选中的',
    '选择要删除的专业' + FF + QM: '选择要删除的专业',
    '专业，回车添' + FF + QM: '专业，回车添加',
    '职责，回车添' + FF + QM: '职责，回车添加',
    '资格，回车添' + FF + QM: '资格，回车添加',
    '基层服务项目岗位吗' + FF + QM: '基层服务项目岗位吗',
    '删除该银行' + FF + QM: '删除该银行',
    '修改社区工作者岗' + FF + QM: '修改社区工作者岗位',
    '完整信息（字段' + FF + QM: '完整信息（字段',
    '未定' + FF + QM: '未定',
    '正高' + FF + QM: '正高级',
    '副高' + FF + QM: '副高级',
    '专科' + FF + QM: '专科',
    '提前' + FF + QM: '提前',
    '综合' + FF + QM: '综合',
    '其他' + FF + QM: '其他',
    '管理' + FF + QM: '管理',
    '热门' + FF + QM: '热门',
    '急招' + FF + QM: '急招',
    '平均' + FF + QM: '平均',
    '最低月' + FF + QM: '最低月薪',
    '最高月' + FF + QM: '最高月薪',
    '社区服务工作' + FF + QM: '社区服务工作者',
    '社区党务工作' + FF + QM: '社区党务工作者',
    '黑龙' + FF + QM: '黑龙江',
    '内蒙' + FF + QM: '内蒙古',
    '一' + FF + QM: '一级',
    '2' + FF + QM: '2年',
    '3' + FF + QM: '3年',
    '9' + FF + QM: '9月',
    '血' + FF + QM: '血站',
    '请输' + FF + QM: '请输入',
    '"如：每年3月' + FF + QM: '"如：每年3-9月',
    '"如：每年6月' + FF + QM: '"如：每年6-9月',
}

sorted_keys = sorted(prefix_fixes.keys(), key=len, reverse=True)

for file_rel in files:
    path = os.path.join(base, file_rel)
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for key in sorted_keys:
        val = prefix_fixes[key]
        if val is not None and key in content:
            content = content.replace(key, val)
    
    if content != original:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        remaining = content.count(FF)
        print(f'{file_rel}: {remaining} remaining (was {original.count(FF)})')
    else:
        print(f'{file_rel}: unchanged')